package Teasy.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Action;
  private ConceptPresentation props_ActiveActionElement;
  private ConceptPresentation props_Actor;
  private ConceptPresentation props_BlockAction;
  private ConceptPresentation props_Configuration;
  private ConceptPresentation props_DataForAction;
  private ConceptPresentation props_Declaration;
  private ConceptPresentation props_DefaultElement;
  private ConceptPresentation props_ElementToReceiveData;
  private ConceptPresentation props_Flow;
  private ConceptPresentation props_InvalidData;
  private ConceptPresentation props_ValidData;
  private ConceptPresentation props_VerifierElement;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Action:
        if (props_Action == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("This file dispatcher a action in system");
          cpb.presentationByName();
          props_Action = cpb.create();
        }
        return props_Action;
      case LanguageConceptSwitch.ActiveActionElement:
        if (props_ActiveActionElement == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("This file represents a element for active a action");
          cpb.presentationByName();
          props_ActiveActionElement = cpb.create();
        }
        return props_ActiveActionElement;
      case LanguageConceptSwitch.Actor:
        if (props_Actor == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("This class represents of the actor in system");
          cpb.presentationByName();
          props_Actor = cpb.create();
        }
        return props_Actor;
      case LanguageConceptSwitch.BlockAction:
        if (props_BlockAction == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("This file contains actions to execute in sequence mode");
          cpb.presentationByName();
          props_BlockAction = cpb.create();
        }
        return props_BlockAction;
      case LanguageConceptSwitch.Configuration:
        if (props_Configuration == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("This file is for configuration test");
          cpb.rawPresentation("Configuration File");
          props_Configuration = cpb.create();
        }
        return props_Configuration;
      case LanguageConceptSwitch.DataForAction:
        if (props_DataForAction == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("This concept represents data for use in action");
          cpb.presentationByName();
          props_DataForAction = cpb.create();
        }
        return props_DataForAction;
      case LanguageConceptSwitch.Declaration:
        if (props_Declaration == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("This file represents a system page file");
          cpb.presentationByName();
          props_Declaration = cpb.create();
        }
        return props_Declaration;
      case LanguageConceptSwitch.DefaultElement:
        if (props_DefaultElement == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("This is a element father");
          cpb.presentationByName();
          props_DefaultElement = cpb.create();
        }
        return props_DefaultElement;
      case LanguageConceptSwitch.ElementToReceiveData:
        if (props_ElementToReceiveData == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("This concept represents for ");
          cpb.presentationByName();
          props_ElementToReceiveData = cpb.create();
        }
        return props_ElementToReceiveData;
      case LanguageConceptSwitch.Flow:
        if (props_Flow == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("This file represents a flow for generate tests using the system described");
          cpb.presentationByName();
          props_Flow = cpb.create();
        }
        return props_Flow;
      case LanguageConceptSwitch.InvalidData:
        if (props_InvalidData == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("This concept represents invalid data for use in data for action file");
          cpb.rawPresentation("Invalid data");
          props_InvalidData = cpb.create();
        }
        return props_InvalidData;
      case LanguageConceptSwitch.ValidData:
        if (props_ValidData == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("For insert valid data");
          cpb.rawPresentation("Valid data");
          props_ValidData = cpb.create();
        }
        return props_ValidData;
      case LanguageConceptSwitch.VerifierElement:
        if (props_VerifierElement == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Element in the page to verifier system status");
          cpb.presentationByName();
          props_VerifierElement = cpb.create();
        }
        return props_VerifierElement;
    }
    return null;
  }
}
