package Teasy.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_identifier extends EnumerationDescriptorBase {

  public EnumerationDescriptor_identifier() {
    super(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0xb2a36ad4ddb5374L, "identifier", "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/804515601402516340", PrimitiveTypeId.STRING);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_ID_0 = new EnumerationDescriptor.MemberDescriptor("ID", "ID", "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/804515601402516341", "ID");
  private final EnumerationDescriptor.MemberDescriptor VALUE_XPATH_0 = new EnumerationDescriptor.MemberDescriptor("XPATH", "XPATH", "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/804515601402516345", "XPATH");
  private final EnumerationDescriptor.MemberDescriptor VALUE_CLASS_CSS_0 = new EnumerationDescriptor.MemberDescriptor("CLASS_CSS", "CLASS CSS", "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/804515601402516342", "CLASS CSS");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_ID_0, VALUE_XPATH_0, VALUE_CLASS_CSS_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "ID":
        return VALUE_ID_0;
      case "XPATH":
        return VALUE_XPATH_0;
      case "CLASS_CSS":
        return VALUE_CLASS_CSS_0;
    }
    return null;
  }
}
