package Teasy.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_selectors extends EnumerationDescriptorBase {

  public EnumerationDescriptor_selectors() {
    super(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e1188470L, "selectors", "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7168771041841939568");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_id_0 = new EnumerationDescriptor.MemberDescriptor("id", "id", 0x637c9747e1188472L, "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7168771041841939570");
  private final EnumerationDescriptor.MemberDescriptor myMember_xpath_0 = new EnumerationDescriptor.MemberDescriptor("xpath", "xpath", 0x637c9747e1188475L, "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7168771041841939573");
  private final EnumerationDescriptor.MemberDescriptor myMember_css_0 = new EnumerationDescriptor.MemberDescriptor("css", "css", 0x637c9747e1188471L, "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7168771041841939569");
  private final EnumerationDescriptor.MemberDescriptor myMember_name_0 = new EnumerationDescriptor.MemberDescriptor("name", "name", 0x637c9747e1188479L, "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7168771041841939577");
  private final EnumerationDescriptor.MemberDescriptor myMember_class_0 = new EnumerationDescriptor.MemberDescriptor("class", "class", 0x637c9747e118847eL, "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7168771041841939582");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e1188470L, 0x637c9747e1188472L, 0x637c9747e1188475L, 0x637c9747e1188471L, 0x637c9747e1188479L, 0x637c9747e118847eL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_id_0, myMember_xpath_0, myMember_css_0, myMember_name_0, myMember_class_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_id_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "id":
        return myMember_id_0;
      case "xpath":
        return myMember_xpath_0;
      case "css":
        return myMember_css_0;
      case "name":
        return myMember_name_0;
      case "class":
        return myMember_class_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
