package Teasy.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_browsers extends EnumerationDescriptorBase {

  public EnumerationDescriptor_browsers() {
    super(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e115f174L, "browsers", "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7168771041841770868");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_chrome_0 = new EnumerationDescriptor.MemberDescriptor("chrome", "chrome", 0x637c9747e115f175L, "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7168771041841770869");
  private final EnumerationDescriptor.MemberDescriptor myMember_firefox_0 = new EnumerationDescriptor.MemberDescriptor("firefox", "firefox", 0x637c9747e115f176L, "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7168771041841770870");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e115f174L, 0x637c9747e115f175L, 0x637c9747e115f176L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_chrome_0, myMember_firefox_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_chrome_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "chrome":
        return myMember_chrome_0;
      case "firefox":
        return myMember_firefox_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
