package Teasy.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ExecuteJavascript_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.newLine();
    tgs.increaseIndent();
    tgs.indent();
    tgs.append("EXECUTE JAVASCRIPT");
    tgs.decreaseIndent();
    tgs.newLine();
    tgs.increaseIndent();
    tgs.indent();
    tgs.append("SCRIPT:");
    tgs.decreaseIndent();
    tgs.append(" ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.function$9UQd));
    tgs.newLine();
    tgs.indent();
    tgs.increaseIndent();
    tgs.indent();
    tgs.append("");
    tgs.decreaseIndent();
  }

  private static final class PROPS {
    /*package*/ static final SProperty function$9UQd = MetaAdapterFactory.getProperty(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x1afad254c1f432fbL, 0x1afad254c1f432fcL, "function");
  }
}
