package Teasy.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class PageRegisterConfig_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("*** Settings ***");
    tgs.newLine();
    tgs.indent();
    tgs.append("Documentation       File to use in page imports");
    tgs.newLine();
    tgs.indent();
    tgs.append("...");
    tgs.newLine();
    tgs.indent();
    tgs.append("...                 All Pages of use tests should in this file.");
    tgs.newLine();
    tgs.newLine();
    tgs.indent();
    for (SNode page : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.pages$S7zd))) {
      tgs.increaseIndent();
      tgs.appendNode(page);
      tgs.decreaseIndent();
    }
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink pages$S7zd = MetaAdapterFactory.getContainmentLink(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x4b2c28ff7a1373d5L, 0x4b2c28ff7a1373d6L, "pages");
  }
}
