package Teasy.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Page_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("*** Settings ***");
    tgs.newLine();
    tgs.indent();
    tgs.append("Documentation       Page of application");
    tgs.newLine();
    tgs.indent();
    tgs.append("...");
    tgs.newLine();
    tgs.indent();
    tgs.append("...                 Contains all keywords (actions) presents in");
    tgs.newLine();
    tgs.indent();
    tgs.append("...                 application page.");
    tgs.newLine();
    tgs.newLine();
    tgs.indent();
    tgs.append("Resource            ../components/components.robot");
    tgs.newLine();
    tgs.newLine();
    tgs.indent();
    tgs.append("*** Keywords ***");
    tgs.newLine();
    for (SNode keyword : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.keyword$FZSf))) {
      tgs.appendNode(keyword);
      tgs.newLine();
    }
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink keyword$FZSf = MetaAdapterFactory.getContainmentLink(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a1L, 0x29b0fffc80bf36a4L, "keyword");
  }
}
