package Teasy.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class WaitUntilPageDoesNotContain_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("    Wait Until Page Does Not Contain    ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.text$YMC$));
    tgs.append("    timeout=");
    tgs.append(Integer.toString(SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.timeout$Yknz)));
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty text$YMC$ = MetaAdapterFactory.getProperty(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x4f2a0581122bf96dL, 0x4f2a0581122bf99cL, "text");
    /*package*/ static final SProperty timeout$Yknz = MetaAdapterFactory.getProperty(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x4f2a0581122bf96dL, 0x4f2a0581122bf96fL, "timeout");
  }
}
